name       : ghostscript
version    : 9.53.3
release    : 23
source     :
    - https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9533/ghostpdl-9.53.3.tar.xz : ebf48e7b4a2d9e5c160f777f6ad48895517d59f75e307633bb1b87992ea35efd
license    : AGPL-3.0-or-later
component  : office
summary    : PostScript language and PDF interpreter
description: |
    Ghostscript is an interpreter for the PostScript language and for PDF. Many other software programs use it in order to convert documentation into various formats.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(jbig2dec)
    - pkgconfig(lcms2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(x11)
    - cups-devel
    - libpaper-devel
setup      : |
    %patch -p1 < $pkgfiles/unwrap-FT_CALLBACK_DEF.patch
    for i in freetype lcms2mt jpeg libpng expat cups/libs jpeg jbig2dec openjpeg tiff zlib expat ; do
        rm -rf $i
    done

    # http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=40dc5b409c6262b18b4bf5386b5482ead4c511e3
    # libs link unwanted to libgpdl that isn't installed
    rm -rf gpdl

    sed -i 's/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac
    %reconfigure --with-drivers=ALL \
                 --disable-compile-inits \
                 --enable-dynamic \
                 --enable-freetype \
                 --with-system-libtiff
build      : |
    %make
    %make so
install    : |
    %make_install
    %make soinstall DESTDIR=$installdir
    install -d -m00755 $installdir/usr/include/ghostscript
    install -m00655 base/*.h $installdir/usr/include/ghostscript
    ln -sv ghostscript $installdir/usr/include/ps
