name       : ghostscript
version    : '9.25'
release    : 19
source     :
    - https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs925/ghostscript-9.25.tar.xz : a2971a23bf15bbd9ddcd173141b15504e51ddc1d5a0a0144b00a6a8b14a62fed
license    : AGPL-3.0-or-later
component  : office
summary    : PostScript language and PDF interpreter
description: |
    Ghostscript is an interpreter for the PostScript language and for PDF. Many other software programs use it in order to convert documentation into various formats.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(x11)
    - cups-devel
    - libpaper-devel
setup      : |
    for i in freetype lcms2 jpeg libpng ; do
        rm -rf $i
    done
    sed -i 's/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac
    %reconfigure --with-drivers=ALL \
                 --disable-compile-inits \
                 --enable-dynamic \
                 --with-system-libtiff
build      : |
    %make
    %make so
install    : |
    %make_install
    %make soinstall DESTDIR=$installdir
    install -d -m00755 $installdir/usr/include/ghostscript
    install -m00655 base/*.h $installdir/usr/include/ghostscript
    ln -sv ghostscript $installdir/usr/include/ps
