name       : ghostscript
version    : '9.20'
release    : 10
source     :
    - https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs920/ghostscript-9.20.tar.gz : 949b64b46ecf8906db54a94ecf83ab97534ebf946f770d3c3f283cb469cb6e14
license    : AGPL
component  : office
summary    : PostScript language and PDF interpreter
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libtiff-4)
    - pkgconfig(lcms2)
    - pkgconfig(libpng15)
    - libjpeg-turbo-devel
    - cups-devel
    - libpaper-devel
description: |
    Ghostscript is an interpreter for the PostScript language and for PDF. Many other software programs use it in order to convert documentation into various formats.
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-7207.patch
    for i in freetype lcms2 jpeg libpng ; do
        rm -rf $i
    done
    sed -i 's/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac configure
    %configure --with-drivers=ALL \
               --disable-compile-inits \
               --enable-dynamic \
               --with-system-libtiff
build      : |
    %make
    %make so
install    : |
    %make_install
    %make soinstall DESTDIR=$installdir
    install -d -D -m 00755 $installdir/usr/include/ghostscript
    install -m00655 base/*.h $installdir/usr/include/ghostscript
    ln -sv ghostscript $installdir/usr/include/ps
