name       : ghostscript
version    : '9.50'
release    : 20
source     :
    - https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs950/ghostpdl-9.50.tar.xz : eeaa4ef815f3871ff831ecf4b7e09ad472b47e8ea8e0fe8d59cac9aeda8355ff
license    : AGPL-3.0-or-later
component  : office
summary    : PostScript language and PDF interpreter
description: |
    Ghostscript is an interpreter for the PostScript language and for PDF. Many other software programs use it in order to convert documentation into various formats.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(x11)
    - cups-devel
    - libpaper-devel
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2019-14869.patch
    for i in freetype lcms2 jpeg libpng ; do
        rm -rf $i
    done

    # http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=40dc5b409c6262b18b4bf5386b5482ead4c511e3
    # libs link unwanted to libgpdl that isn't installed
    rm -rf gpdl

    sed -i 's/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac
    %reconfigure --with-drivers=ALL \
                 --disable-compile-inits \
                 --enable-dynamic \
                 --with-system-libtiff
build      : |
    %make
    %make so
install    : |
    %make_install
    %make soinstall DESTDIR=$installdir
    install -d -m00755 $installdir/usr/include/ghostscript
    install -m00655 base/*.h $installdir/usr/include/ghostscript
    ln -sv ghostscript $installdir/usr/include/ps
