name       : ghostscript
version    : '9.18'
release    : 7
source     :
    - http://downloads.ghostscript.com/public/old-gs-releases/ghostscript-9.18.tar.gz : 5fc93079749a250be5404c465943850e3ed5ffbc0d5c07e10c7c5ee8afbbdb1b
license    : AGPL
component  : office
summary    : PostScript language and PDF interpreter
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libtiff-4)
    - pkgconfig(lcms2)
    - pkgconfig(libpng15)
    - libjpeg-turbo-devel
    - cups-devel
    - libpaper-devel
description: |
    Ghostscript is an interpreter for the PostScript language and for PDF. Many other software programs use it in order to convert documentation into various formats.
setup      : |
    for i in freetype lcms2 jpeg libpng ; do
        rm -rf $i
    done
    sed -i 's/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac configure
    %configure --with-drivers=ALL \
               --disable-compile-inits \
               --enable-dynamic \
               --with-system-libtiff
build      : |
    %make
    %make so
install    : |
    %make_install
    %make soinstall DESTDIR=$installdir
    install -d -D -m 00755 $installdir/usr/include/ghostscript
    install -m00655 base/*.h $installdir/usr/include/ghostscript
    ln -sv ghostscript $installdir/usr/include/ps
